### ISSUE TITLE
Demo video

### ISSUE THREAD

**Issue by ArminJo** [8bitbuddhist/PixelMaestro#9]
Hi
is there a demo video available to see all the effects, or at least some of them?

**Comment by 8bitbuddhist** [comment]
Not at the moment, but I'm planning on making one.

**Comment by 8bitbuddhist** [comment]
I added short GIFs of each animation to the documentation. It only shows the base animations, but it'll at least give you an idea of what they look like.

https://8bitbuddhist.github.io/PixelMaestro/Animations.html
